spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codeify
    username: root
    password: kEMICEK123**
  flyway:
    enabled: true
    repair: true
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: codeify.limited.info@gmail.com
    password: fbdz ycvi wmlt nbqv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  client:
    url: http://localhost:3000